- name: set hostname
  hostname: name={{ hostname }}

- name: copy hostsfile
  copy: src=hosts
        dest=/etc/hosts

- name: add mesos key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xE56151BF state=present

- name: add mesos repo
  apt_repository: repo='deb http://repos.mesosphere.io/ubuntu trusty main' state=present

- name: update apt
  apt: update_cache=yes

- name: install zookeeper
  apt: pkg=zookeeperd
  notify:
    - restart zookeeper

- name: put zookeeper conf
  copy: src=zoo.cfg
        dest=/etc/zookeeper/conf/zoo.cfg
  notify:
    - restart zookeeper

- name: set my zookeeper id
  template: src=myid.j2 dest=/var/lib/zookeeper/myid
  notify:
    - restart zookeeper
