---
- include: install-mesos.yml

- include: zookeeper.yml
  when: '"mesos-masters" in group_names'

- include: mesos-master.yml
  when: '"mesos-masters" in group_names'

- include: mesos-slave.yml
  when: '"mesos-slaves" in group_names'
